### ISSUE TITLE
Rows disappearing, or being invisible after todays bugfix patch

### ISSUE THREAD

**Issue by junhojin123** [laiglinne-ff/Project_TheStone#7]
[The oeverlay, after the first run, acts weird and starts omitting rows, and fully breaks after a few pulls](https://i.imgur.com/txuthUK.png)

edit: i saw date wrong and see there was no patch today, but still an issue

**Comment by junhojin123** [comment]
the bug doesnt happen when i disable the animated ranking feature

**Comment by laiglinne-ff** [comment]
It fixed https://github.com/laiglinne-ff/Project_TheStone/commit/c6f75f9a5c0fc86a3b63a5762ac8a3ff46bd872f
