### ISSUE TITLE
LB damage is being calculated into personal dps

### ISSUE THREAD

**Issue by junhojin123** [laiglinne-ff/Project_TheStone#8]
doesnt matter who lbs, the damage is being added to personal dps

**Comment by laiglinne-ff** [comment]
https://github.com/laiglinne-ff/Project_TheStone/commit/c6f75f9a5c0fc86a3b63a5762ac8a3ff46bd872f

Sorry. it's Cleaveore 2.1.3 Bug. i fixing now. downgrade Cleaveore.js now

**Comment by junhojin123** [comment]
i dont even know what it means to downgrade Cleaveore.js...
